services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  main:
    image: main:latest
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5

  mail:
    image: mail:latest
    build:
      context: ./mail
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - main
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=mail
      - LOG_FILENAME=/app/logs/mail_serice.log
    volumes:
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  ai:
    image: ai:latest
    build:
      context: ./ai
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=main
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  rabbitmq_data:
  logs:
