services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  main:
    image: main:latest
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq

  mail:
    image: mail:latest
    build:
      context: ./mail
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - main
    environment:
      - RABBITMQ_HOST=rabbitmq
      - QUEUE_NAME=main # change for any queue you need
      - LOG_FILENAME=/app/logs/mail_serice.log
    volumes:
      - ./logs:/app/logs


volumes:
  rabbitmq_data:

# TODO: check if mail service volume work correctly